### PR TITLE
add missing type for onError prop

### PR DESCRIPTION
**Pull request by benji24290**

### CODE REVIEW

**Comment by benji24290** [comment]
i got the type from: https://pay.sandbox.datatrans.com/upp/payment/js/datatrans-2.0.0.global.js, since it is a js file i am unable to know the exact type of the two props.
```js
if (typeof event.data === 'object' && event.data.type === 'error') {
       if (typeof config.error === 'function') {
             var errorData = {
                        message: event.data.message,
                        detail: event.data.detail
             };

            config.error(errorData);
       }
       cleanup();
       return;
 }

**Comment by benji24290** [comment]
@jantimon do you think this PR could be merged? If you want I can make a fitting issue for this PR.
(sorry for tagging you, I just saw that you made the last type changes)

**Comment by n3ssi3** [comment]
@benji24290 Thank you, I will merge it now

**Comment by benji24290** [comment]
thank you! 🎉

**Comment by n3ssi3** [comment]
@benji24290 we will push it to npm next week.

**Comment by pstadler** [comment]
This is now released with [4.0.1](https://github.com/datatrans/react-datatrans-light-box/releases/tag/4.0.1). Thank you!

**Pull request merged**
